AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SMSServicePackageS3Bucket:
    Type: String
    Default: sms-service-package-bucket
    Description: SMS delievery service package bucket
  SMSServicePackage:
    Type: String
    Default: SMSServicePackage.zip
  EmailServicePackageS3Bucket:
    Type: String
    Default: email-service-package-bucket
    Description: Email delivery service package bucket
  EmailServiceArtifact:
    Type: String
    Default: EmailServiceArtifact.zip
    Description: Email service artifact to be deployed

Resources:
  # SMS delivery service esources
  SMSDeliveryLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - logs:*
                Resource: arn:aws:logs:*:*:*
      Policies:
        - PolicyName: LambdaAllowSQS
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                Resource: !GetAtt SMSDeliveryQueue.Arn

  SMSDeliveryLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: SMSDeliveryLambdaFunction::SMSDeliveryLambdaFunction.Function::FunctionHandler
      Role: !GetAtt SMSDeliveryLambdaRole.Arn
      FunctionName: SMSDeliveryLambdaFunction
      Code:
        S3Bucket: !Ref SMSServicePackageS3Bucket
        S3Key: !Ref SMSServicePackage
      Runtime: dotnet6
      MemorySize: 128
      Timeout: 30

  SMSDeliveryQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      VisibilityTimeout: 30

 

  SMSDeliveryLambdaSQSTrigger:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      EventSourceArn: !GetAtt SMSDeliveryQueue.Arn
      FunctionName: !GetAtt SMSDeliveryLambdaFunction.Arn
      Enabled: True

  #common to both set of resources
  SNSTopic:
    Type: "AWS::SNS::Topic"

  # Email deliver service resources
  EmailDeliveryQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      VisibilityTimeout: 30

  EmailDeliveryLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - logs:*
                Resource: arn:aws:logs:*:*:*
      Policies:
        - PolicyName: LambdaAllowSQS
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt EmailDeliveryQueue.Arn

  EmailDeliveryLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: EmailDeliveryProcessorLambdaFunction::EmailDeliveryProcessorLambdaFunction.Function::FunctionHandler
      Role: !GetAtt EmailDeliveryLambdaRole.Arn
      FunctionName: EmailDeliveryLambdaFunction
      Code:
        S3Bucket: !Ref SMSServicePackageS3Bucket
        S3Key: !Ref EmailServiceArtifact
      Runtime: dotnet6
      MemorySize: 512
      Timeout: 30

  #arrow between queue and lambda
  EmailDeliveryLambdaSQSTrigger:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      EventSourceArn: !GetAtt EmailDeliveryQueue.Arn
      FunctionName: !GetAtt EmailDeliveryLambdaFunction.Arn
      Enabled: True
